### PR TITLE
Add entypo icons

### PR DESCRIPTION
**Pull request by iacore**
The icons are in SVG format. Icons are from http://entypo.com/.

A word about tinyvg: the converter is in C#, and needs libssl on Linux to build. It doesn't seem to be developed as twice failed to implement the converter.

It might be better for the project to read SVG directly. You only need to support a subset of SVG for icons.

### CODE REVIEW

**Comment by david-vanderson** [comment]
Thank you!  I've been meaning to look back at the icon situation.  I still like the tinyvg concept.  I'll see how many of these can be converted.

**Comment by david-vanderson** [comment]
How do you download the icon set?  The download link on entypo.com doesn't work for me.

**Comment by iacore** [comment]
The icons are available as files in this PR. I downloaded it with `wget2 -rk https://entypo.com/`

**Comment by david-vanderson** [comment]
Aha - thanks!  I've converted them and replaced the papirus icons.  Look good?

**Comment by david-vanderson** [comment]
Me neither.  The icon set has a bunch of icons for social media and other internet companies, so I figured it was something like that, but 500px.com doesn't have an infinity sign, so maybe it's old.

**Comment by iacore** [comment]
Do you have a community forum? You can enable Github Discussion

**Comment by david-vanderson** [comment]
Thanks - didn't know about Github Discussions but have turned them on.

**Pull request closed without merging**
